2024-07-06 22:22:04,460 INFO    StreamThr :3662 [internal.py:wandb_internal():85] W&B internal server running at pid: 3662, started at: 2024-07-06 22:22:04.458688
2024-07-06 22:22:04,471 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: status
2024-07-06 22:22:04,485 INFO    WriterThread:3662 [datastore.py:open_for_write():87] open: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/run-9g1pvxzl.wandb
2024-07-06 22:22:04,486 DEBUG   SenderThread:3662 [sender.py:send():379] send: header
2024-07-06 22:22:04,491 DEBUG   SenderThread:3662 [sender.py:send():379] send: run
2024-07-06 22:22:08,067 INFO    SenderThread:3662 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x78699bcc55d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 801, in urlopen
    retries = retries.increment(
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x78699bcc55d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/lusitech/ComputerVision/PotholeDetection/venv/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x78699bcc55d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2024-07-06 22:22:09,496 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: keepalive
2024-07-06 22:22:14,498 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: keepalive
2024-07-06 22:22:19,501 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: keepalive
2024-07-06 22:22:24,502 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: keepalive
2024-07-06 22:22:29,505 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: keepalive
2024-07-06 22:22:34,508 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: keepalive
2024-07-06 22:22:39,509 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: keepalive
2024-07-06 22:22:42,100 INFO    SenderThread:3662 [dir_watcher.py:__init__():211] watching files in: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files
2024-07-06 22:22:42,101 INFO    SenderThread:3662 [sender.py:_start_run_threads():1188] run started: 9g1pvxzl with start time 1720304524.467996
2024-07-06 22:22:42,102 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: status_report
2024-07-06 22:22:42,129 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: check_version
2024-07-06 22:22:42,129 DEBUG   SenderThread:3662 [sender.py:send_request():406] send_request: check_version
2024-07-06 22:22:43,474 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: run_start
2024-07-06 22:22:43,504 DEBUG   HandlerThread:3662 [system_info.py:__init__():26] System info init
2024-07-06 22:22:43,504 DEBUG   HandlerThread:3662 [system_info.py:__init__():41] System info init done
2024-07-06 22:22:43,504 INFO    HandlerThread:3662 [system_monitor.py:start():194] Starting system monitor
2024-07-06 22:22:43,505 INFO    SystemMonitor:3662 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-07-06 22:22:43,505 INFO    HandlerThread:3662 [system_monitor.py:probe():214] Collecting system info
2024-07-06 22:22:43,506 INFO    SystemMonitor:3662 [interfaces.py:start():188] Started cpu monitoring
2024-07-06 22:22:43,507 INFO    SystemMonitor:3662 [interfaces.py:start():188] Started disk monitoring
2024-07-06 22:22:43,510 INFO    SystemMonitor:3662 [interfaces.py:start():188] Started gpu monitoring
2024-07-06 22:22:43,512 INFO    SystemMonitor:3662 [interfaces.py:start():188] Started memory monitoring
2024-07-06 22:22:43,513 INFO    SystemMonitor:3662 [interfaces.py:start():188] Started network monitoring
2024-07-06 22:22:43,523 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:43,523 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:43,537 DEBUG   HandlerThread:3662 [system_info.py:probe():152] Probing system
2024-07-06 22:22:43,542 DEBUG   HandlerThread:3662 [gitlib.py:_init_repo():56] git repository is invalid
2024-07-06 22:22:43,542 DEBUG   HandlerThread:3662 [system_info.py:probe():200] Probing system done
2024-07-06 22:22:43,542 DEBUG   HandlerThread:3662 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.12', 'heartbeatAt': '2024-07-06T22:22:43.537929', 'startedAt': '2024-07-06T22:22:04.415090', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'host': 'lusitech', 'username': 'lusitech', 'executable': '/home/lusitech/ComputerVision/PotholeDetection/venv/bin/python', 'cpu_count': 2, 'cpu_count_logical': 4, 'cpu_freq': {'current': 1300.003, 'min': 400.0, 'max': 2800.0}, 'cpu_freq_per_core': [{'current': 1300.004, 'min': 400.0, 'max': 2800.0}, {'current': 1299.994, 'min': 400.0, 'max': 2800.0}, {'current': 1299.999, 'min': 400.0, 'max': 2800.0}, {'current': 1299.995, 'min': 400.0, 'max': 2800.0}], 'disk': {'/': {'total': 95.56452178955078, 'used': 87.78219604492188}}, 'gpu': 'NVIDIA GeForce 940MX', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce 940MX', 'memory_total': 2147483648}], 'memory': {'total': 15.466697692871094}}
2024-07-06 22:22:43,542 INFO    HandlerThread:3662 [system_monitor.py:probe():224] Finished collecting system info
2024-07-06 22:22:43,543 INFO    HandlerThread:3662 [system_monitor.py:probe():227] Publishing system info
2024-07-06 22:22:43,543 INFO    HandlerThread:3662 [system_monitor.py:probe():229] Finished publishing system info
2024-07-06 22:22:43,555 DEBUG   SenderThread:3662 [sender.py:send():379] send: files
2024-07-06 22:22:43,556 INFO    SenderThread:3662 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-07-06 22:22:43,902 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: python_packages
2024-07-06 22:22:43,903 DEBUG   SenderThread:3662 [sender.py:send_request():406] send_request: python_packages
2024-07-06 22:22:43,916 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: stop_status
2024-07-06 22:22:43,917 DEBUG   SenderThread:3662 [sender.py:send_request():406] send_request: stop_status
2024-07-06 22:22:43,920 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:44,109 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_created():271] file/dir created: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/wandb-metadata.json
2024-07-06 22:22:44,109 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_created():271] file/dir created: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/requirements.txt
2024-07-06 22:22:44,477 DEBUG   SenderThread:3662 [sender.py:send():379] send: telemetry
2024-07-06 22:22:44,913 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:45,103 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_created():271] file/dir created: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/output.log
2024-07-06 22:22:45,525 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:45,526 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:45,915 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:46,087 INFO    wandb-upload_0:3662 [upload_job.py:push():130] Uploaded file /tmp/tmpe_kunxe4wandb/eczay0lz-wandb-metadata.json
2024-07-06 22:22:46,915 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:47,104 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/output.log
2024-07-06 22:22:47,406 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: status_report
2024-07-06 22:22:47,527 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:47,527 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:47,916 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:48,915 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:49,107 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/output.log
2024-07-06 22:22:49,532 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:49,533 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:49,916 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:50,958 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:51,108 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/output.log
2024-07-06 22:22:51,535 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:51,535 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:51,959 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:52,794 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: status_report
2024-07-06 22:22:53,007 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:53,109 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/output.log
2024-07-06 22:22:53,536 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:53,536 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:54,007 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:55,013 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:55,109 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/output.log
2024-07-06 22:22:55,538 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:55,538 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:56,021 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:57,016 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:57,539 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:57,539 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:57,933 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: status_report
2024-07-06 22:22:58,012 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:58,912 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: stop_status
2024-07-06 22:22:58,914 DEBUG   SenderThread:3662 [sender.py:send_request():406] send_request: stop_status
2024-07-06 22:22:59,014 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:22:59,541 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:22:59,541 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:23:00,030 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:23:01,043 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:23:01,115 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/output.log
2024-07-06 22:23:01,542 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:23:01,543 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:23:02,193 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:23:03,116 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/output.log
2024-07-06 22:23:03,282 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: status_report
2024-07-06 22:23:03,350 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:23:03,545 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:23:03,546 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:23:04,380 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:23:05,117 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/output.log
2024-07-06 22:23:05,389 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:23:05,549 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:23:05,549 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:23:06,390 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:23:07,119 INFO    Thread-12 :3662 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/lusitech/ComputerVision/PotholeDetection/training/wandb/run-20240706_222204-9g1pvxzl/files/output.log
2024-07-06 22:23:07,390 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-06 22:23:07,550 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:23:07,550 ERROR   gpu       :3662 [interfaces.py:monitor():142] Failed to sample metric: Not Supported
2024-07-06 22:23:08,304 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: status_report
2024-07-06 22:23:08,397 DEBUG   HandlerThread:3662 [handler.py:handle_request():158] handle_request: internal_messages
                                                                                                                                                                                                                 